name: Build Web app
on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: 16
      - name: build
        run: |
          npm ci
          npm run build
      - uses: actions/upload-artifact@v3
        with:
          name: tap-webapp
          path: packages/web-client/build/*
      - name: archive-backend
        run: |
          npm ci --only-production --workspace packages/backend
          mkdir tap-backend
          mv packages/backend/index.js tap-backend/index.js
          mv packages/backend/lib tap-backend/lib
          mv node_modules tap-backend/node_modules
          tar -caf tap-backend.tar.gz tap-backend/*
      - uses: actions/upload-artifact@v3
        with:
          name: tap-backend
          path: tap-backend.tar.gz
